kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "angular-openshift-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/douglaslmiller/angular-openshift"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile
